{% set version = '2018-4.17' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvmmin
  version: {{ version|replace("-", "_") }}

source:
  fn: Rvmmin_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Rvmmin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rvmmin/Rvmmin_{{ version }}.tar.gz
  sha256: d53ba7ab06596a47990caf101a50935b2b34402f9dd8414f098a873026ff1f56

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-optextras
  run:
    - r-base
    - r-optextras

test:
  commands:
    - $R -e "library('Rvmmin')"           # [not win]
    - "\"%R%\" -e \"library('Rvmmin')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rvmmin
  license: GPL (>= 2)
  summary: Variable metric nonlinear function minimization with bounds constraints.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
