{% set version = "2018-4.17.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvmmin
  version: {{ version|replace("-", "_") }}

source:
  fn: Rvmmin_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Rvmmin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rvmmin/Rvmmin_{{ version }}.tar.gz
  sha256: 55000ac4ff57d42f172c46c7d6b0a603da3b65866d6440d6b32bac4d2b81814e

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-optextras
  run:
    - r-base
    - r-optextras

test:
  commands:
    - $R -e "library('Rvmmin')"           # [not win]
    - "\"%R%\" -e \"library('Rvmmin')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rvmmin
  license: GPL (>= 2)
  summary: Variable metric nonlinear function minimization with bounds constraints.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
