appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: PgP89DkdUKzo9vTfywrrUQNpqTBMrcZfhGzzpjIGJ/Px6HY0SbNivtvy6k0KkYTOckA6bIdD+6YZCWn43B6XmpcrIV4by0ZkiC0nuJSn5vIjzlihseBZGVBZAUORidj89tWqfEvdeE8P6XYhBezCsUXiSkhKpg0KPbnxjKF78PLKqmj5OnsNrUa41XCID2guz8k13Vo/g+ehHufpa1y5JZmhX8JU0CcZAVYiRxt0XD3//wqjieSa1v2SQnxDOnCTFosDECCgAq4W9/lkaOKVzYGb/DU9lTBb0MLeDREOBSvWPDhxaIa8fcOMT84pDu0Q+SsZjOLyZhsB4fydvY2PukP4pmYce5T0jw9RGtFL+iayL4af1xqrMaUb0qUKlxkda4db7JlwAQl93t5tsTZ6u4oSrk4PiP6xx4MzF5AjxBuQriNhm7MtHI5t36blkyki3ll1MAzYV291psB89uq+jvH3UK4kIWgLRJ6ug/+/1GCIv/7Vk9pECwndm58f9LPF1ZFSf654+4yrgkEyOrNCYNLtxGfPrxEptr8ALqPqrNrLU5V0unxSWmP6Bqp3AHltmH1xafJ4OYoeeSQaC8KABpMF3owzuI1A7pNPgYyv7TOgAiN5/x9K32py4VG6/gyChkgNuwk3WceLMeaz9vEyVOyU4KlzCD4zYeGKNFBAV3g=}
