travis:
  secure:
    BINSTAR_TOKEN: OqOWSnJyrIuMcV5cubfC6p1A+aPA/ZG7of6x5MgMzBHG5YBjaTX42QNhHO1zHR3EvgUJ6uVrqiyxIwEy0Id/PInCInczmCAqNv/2wQ7BHYGNV6WYu0A/OJgcWohg+uVW0pCpBW+zYvXbGtMNGVtGbWZinn85GkGf6x1I0GEiiYSucy+g1gUS5MOurEeK6NHI8inIl+wCfgpobW+hb59vu+ZIAbKj6ZsAVmCkI8kVE2E+jTCixJdz1GWKxwu72488Pm1ljAnkJEZ+lDwwp4b54JDhsjvRphoo96hqQOTjxDprUhChTkH3F1B4n75WInl6nbcudQU6kAPaelRFYLbMbZeuLNa/t6VKi9XoAQa3RM3VRZBVifae1T/H9vcJb6kVqsO5NnM03nv19WtRj9sYL9ZGxFNw/vYaEFhe0NavaqvrooV2uKQv62OIrOSfNJgmXTgP7iVJOEu0WNTVY4ravDKfcdArc05H+6Dki2iOJHlTMcKpAbOgTS+NiTGaA56LSNeU1kbNRBZdx9XBnjeYOAjx7u0XMgQJ68VRQ1xZI5Vol7uF+JaXOt3RYw+E5Et6AZ/SKwI8Sq/+kZrhu9UuguC7llOxLNqd8bB9d5qyOmeM6JRivlrAwpU3Qxn43WhduUR1jjbwe3jFH09ik76nKk9YpX+KaPXRmC0Rg93zLP0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
