travis:
  secure:
    BINSTAR_TOKEN: LBqcxp7uRW6d3TJZGq9XLB1KZwACrbePdYFAXAogis/++bgAcSTwSz5WesOYb59CM3oljrmT4yPk7uQQaNzyvvT7ojjv+XEMiCN253AccvCNuAsgu0BGHcwrSfvIinrirpjiJo1eCJ4nAzfnjAljL2N7vt18pkZWtd0NSaSdy5/eHUE0vCTQm8OvP7UXsNO+ZP1Ziw6wEz8cCxTL7ryWgLtz912HpIAyMVNJAoVy8iI1MVDQ0n89cy5IOg9omZR39tAYGXTe3tRd8aqyB2JSrN/ReyG6e/4MNIIdSRiTYBLUe3/auhP0yHjm9vYgvy6u51+WB3G8mbWmmQ07gULZb0ecJH5OqWq0sg9k+FVuK5rqfiEppnbmTYuAz5uzXWW/WsAepGyrDc+gda5+p3eA8epWj81vpj/Pnid8izpwVgc9e69+Lpw6MfqSAZuErMxolUeem6ReS+Mc5mjxHZ+3///2fkiwX8vX18teLIR/xEFyHaZxTZEuZTRRloNOhCNYQigz6HoorO6gNNn2KBN5tj77ZmyYWP4t0bJSQh9tlD0BT6yusrpkcl8oSMRcAukNMkGr99Q9gPUOaBmY8NeR8ta70ZRw/hV8ApeTxpvJ+QL+L3jXGNesrILrOWaJOIWMwlU69HO83W+bOptPzav7Aqr/ttRCRC5ZsCkA9AGtnAE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
